### ISSUE TITLE
bug: Manager crashing when allowing permissions and adding apk

### ISSUE THREAD

**Issue by GR3YH4TT3R93** [ReVanced/revanced-manager#1110]
### Type

Error while running the manager

### Bug description

When opening Manager the first time, you're prompted to enable permissions, upon doing so the app crashes (permissions added manually) and when trying to add YouTube apk from storage, Revanced Manager flickers and opens to the home page instead of opening the patch selector.

### Steps to reproduce

Step 1: install fresh version of manager

Step 2: open app

Step 3: enable first permission

Step 4: press back

Step 5: open app settings, enable permissions

Step 6: open app, open patcher, select apk from storage

Step 7: app crashes to app home screen

### Android version

13

### Manager version

1.7.0

### Target package name

com.google.youtube

### Target package version.

18.23.35

### Installation type

Non-root

### Patches selected.

N/A

### Device logs (exported using Manager settings).

```shell
--------- beginning of crash
08-07 19:47:10.435 15126 15126 E AndroidRuntime: FATAL EXCEPTION: main
08-07 19:47:10.435 15126 15126 E AndroidRuntime: Process: app.revanced.manager.flutter, PID: 15126
08-07 19:47:10.435 15126 15126 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=210, result=0, data=null} to activity {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.baseflow.permissionhandler.PermissionManager$RequestPermissionsSuccessCallback.onSuccess(java.util.Map)' on a null object reference
08-07 19:47:10.435 15126 15126 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5061)
08-07 19:47:10.435 15126 15126 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5104)
08-07 19:47:10.435 15126 15126 E AndroidRuntime: 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:60)
08-07 19:47:10.435 15126 15126 E AndroidRuntime: 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
08-07 19:47:10.435 15126 15126 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
08-07 19:47:10.435 15126 15126 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
08-07 19:47:10.435 15126 15126 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2466)
08-07 19:47:10.435 15126 15126 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
08-07 19:47:10.435 15126 15126 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:240)
08-07 19:47:10.435 15126 15126 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:351)
08-07 19:47:10.435 15126 15126 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8364)
08-07 19:47:10.435 15126 15126 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-07 19:47:10.435 15126 15126 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
08-07 19:47:10.435 15126 15126 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
08-07 19:47:10.435 15126 15126 E AndroidRuntime: Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=210, result=0, data=null} to activity {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.baseflow.permissionhandler.PermissionManager$RequestPermissionsSuccessCallback.onSuccess(java.util.Map)' on a null object reference
08-07 19:47:10.435 15126 15126 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5655)
08-07 19:47:10.435 15126 15126 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5036)
08-07 19:47:10.435 15126 15126 E AndroidRuntime: 	... 13 more
08-07 19:47:10.435 15126 15126 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.baseflow.permissionhandler.PermissionManager$RequestPermissionsSuccessCallback.onSuccess(java.util.Map)' on a null object reference
08-07 19:47:10.435 15126 15126 E AndroidRuntime: 	at com.baseflow.permissionhandler.PermissionManager.onActivityResult(PermissionManager.java:101)
08-07 19:47:10.435 15126 15126 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:809)
08-07 19:47:10.435 15126 15126 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:432)
08-07 19:47:10.435 15126 15126 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:872)
08-07 19:47:10.435 15126 15126 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:917)
08-07 19:47:10.435 15126 15126 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:8731)
08-07 19:47:10.435 15126 15126 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5648)
08-07 19:47:10.435 15126 15126 E AndroidRuntime: 	... 14 more
08-07 19:47:20.895 17682 17682 E AndroidRuntime: FATAL EXCEPTION: main
08-07 19:47:20.895 17682 17682 E AndroidRuntime: Process: app.revanced.manager.flutter, PID: 17682
08-07 19:47:20.895 17682 17682 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=212, result=-1, data=null} to activity {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.app.Activity.getPackageManager()' on a null object reference
08-07 19:47:20.895 17682 17682 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5061)
08-07 19:47:20.895 17682 17682 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5104)
08-07 19:47:20.895 17682 17682 E AndroidRuntime: 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:60)
08-07 19:47:20.895 17682 17682 E AndroidRuntime: 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
08-07 19:47:20.895 17682 17682 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
08-07 19:47:20.895 17682 17682 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
08-07 19:47:20.895 17682 17682 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2466)
08-07 19:47:20.895 17682 17682 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
08-07 19:47:20.895 17682 17682 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:240)
08-07 19:47:20.895 17682 17682 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:351)
08-07 19:47:20.895 17682 17682 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8364)
08-07 19:47:20.895 17682 17682 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-07 19:47:20.895 17682 17682 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
08-07 19:47:20.895 17682 17682 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
08-07 19:47:20.895 17682 17682 E AndroidRuntime: Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=212, result=-1, data=null} to activity {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.app.Activity.getPackageManager()' on a null object reference
08-07 19:47:20.895 17682 17682 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5655)
08-07 19:47:20.895 17682 17682 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5036)
08-07 19:47:20.895 17682 17682 E AndroidRuntime: 	... 13 more
08-07 19:47:20.895 17682 17682 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.app.Activity.getPackageManager()' on a null object reference
08-07 19:47:20.895 17682 17682 E AndroidRuntime: 	at com.baseflow.permissionhandler.PermissionManager.onActivityResult(PermissionManager.java:78)
08-07 19:47:20.895 17682 17682 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:809)
08-07 19:47:20.895 17682 17682 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:432)
08-07 19:47:20.895 17682 17682 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:872)
08-07 19:47:20.895 17682 17682 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:917)
08-07 19:47:20.895 17682 17682 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:8731)
08-07 19:47:20.895 17682 17682 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5648)
08-07 19:47:20.895 17682 17682 E AndroidRuntime: 	... 14 more
--------- beginning of system
08-08 14:23:56.791 15802 15802 D OplusInputMethodUtil: init sDebug to false, init sDebugIme to false, init sAlwaysOn to false
08-08 14:23:56.791 15802 15802 D OplusInputMethodUtil: updateDebugToClass InputMethodManager.DEBUG = false
08-08 14:23:56.791 15802 15802 D OplusInputMethodUtil: updateDebugToClass ImeFocusController.DEBUG = false
08-08 14:23:56.791 15802 15802 D OplusInputMethodUtil: updateDebugToClass BaseInputConnection.DEBUG = false
08-08 14:23:56.791 15802 15802 D OplusInputMethodUtil: updateDebugToClass ImeFocusController.sDebugIme = false
08-08 14:23:56.857 15802 15802 V ZoomWindowDecorView: setLastReportedMergedConfiguration mZoomDisplayHeight: 2400 getDecorView.8992552
08-08 14:23:56.876 15802 15802 I Quality : Skipped: false 1 cost 24.605333 refreshRate 16590010 bit true processName app.revanced.manager.flutter
08-08 14:23:57.341 15802 15802 I Quality : Skipped: false 22 cost 373.43243 refreshRate 16587417 bit true processName app.revanced.manager.flutter
08-08 14:24:03.473 15802 15802 D OplusInputMethodManagerInternal: get inputMethodManager extension: com.android.internal.view.IInputMethodManager$Stub$Proxy@3ea50e6
08-08 14:24:13.771 15802 15802 I Quality : Skipped: false 1 cost 27.137354 refreshRate 16591857 bit true processName app.revanced.manager.flutter
08-08 14:24:47.977 15802 15802 V ZoomWindowDecorView: removeZoomView
08-08 14:24:52.874 18825 18825 D OplusInputMethodUtil: init sDebug to false, init sDebugIme to false, init sAlwaysOn to false
08-08 14:24:52.874 18825 18825 D OplusInputMethodUtil: updateDebugToClass InputMethodManager.DEBUG = false
08-08 14:24:52.874 18825 18825 D OplusInputMethodUtil: updateDebugToClass ImeFocusController.DEBUG = false
08-08 14:24:52.874 18825 18825 D OplusInputMethodUtil: updateDebugToClass BaseInputConnection.DEBUG = false
08-08 14:24:52.874 18825 18825 D OplusInputMethodUtil: updateDebugToClass ImeFocusController.sDebugIme = false
08-08 14:24:52.919 18825 18825 V ZoomWindowDecorView: setLastReportedMergedConfiguration mZoomDisplayHeight: 2400 getDecorView.8992552
08-08 14:24:53.333 18825 18825 I Quality : Skipped: false 25 cost 420.67395 refreshRate 16586506 bit true processName app.revanced.manager.flutter
08-08 14:24:56.225 18825 18825 D OplusInputMethodManagerInternal: get inputMethodManager extension: com.android.internal.view.IInputMethodManager$Stub$Proxy@12da0d4
08-08 14:24:59.006 18825 18825 I Quality : Skipped: false 1 cost 22.862673 refreshRate 16586765 bit true processName app.revanced.manager.flutter
08-08 14:24:59.699 18825 18825 V ZoomWindowDecorView: removeZoomView
08-08 14:25:02.545 18825 18825 D ActivityThread: do gfx trim 40 success
08-08 14:25:03.215 18825 18825 I Quality : Skipped: false 18 cost 300.47113 refreshRate 16587422 bit true processName app.revanced.manager.flutter
08-08 14:25:03.223 18825 18825 V ZoomWindowDecorView: setLastReportedMergedConfiguration mZoomDisplayHeight: 2400 getDecorView.214952411
08-08 14:25:05.499 18825  5412 I Quality : Blocked msg = Package name: app.revanced.manager.flutter [ schedGroup: 5 schedPolicy: 0 ] process the message: { when=-1s109ms what=0 target=android.os.Handler callback=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0 } took 1109 ms
08-08 14:25:17.272 18825 18825 V ZoomWindowDecorView: removeZoomView
08-08 14:25:18.493 18825 18825 I Quality : Skipped: false 17 cost 299.464 refreshRate 16666666 bit true processName app.revanced.manager.flutter
--------- beginning of main
08-08 14:25:18.495 18825 18825 I SurfaceView: 94088684 onAttachedToWindow
08-08 14:25:18.500 18825 18825 D BufferQueueConsumer: [](id:498900000004,api:0,p:-1,c:18825) connect: controlledByApp=false
08-08 14:25:18.500 18825 18825 E IPCThreadState: attemptIncStrongHandle(51): Not supported
08-08 14:25:18.501 18825 18825 V ZoomWindowDecorView: setLastReportedMergedConfiguration mZoomDisplayHeight: 2400 getDecorView.123045974
08-08 14:25:18.501 18825  5414 D BufferQueueProducer: [VRI[MainActivity]#4(BLAST Consumer)4](id:498900000004,api:1,p:18825,c:18825) connect: api=1 producerControlledByApp=true
08-08 14:25:18.503 18825 18825 D BufferQueueConsumer: [](id:498900000005,api:0,p:-1,c:18825) connect: controlledByApp=false
08-08 14:25:18.504 18825 18825 I SurfaceView: 94088684 visibleChanged -- surfaceCreated 
08-08 14:25:18.504 18825  7242 D BufferQueueProducer: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#5(BLAST Consumer)5](id:498900000005,api:1,p:18825,c:18825) connect: api=1 producerControlledByApp=true
08-08 14:25:18.506 18825 18825 I SurfaceView: 94088684 surfaceChanged -- format=4 w=1080 h=2400
08-08 14:25:18.517 18825  7241 I flutter : dynamic_color: Core palette detected.
08-08 14:25:18.543 18825 18825 E SurfaceSyncer: Failed to find sync for id=0
08-08 14:25:18.543 18825 18825 D VRI[MainActivity]: registerCallbacksForSync syncBuffer=false
08-08 14:25:18.549 18825  5414 D VRI[MainActivity]: Received frameCommittedCallback lastAttemptedDrawFrameNum=1 didProduceBuffer=true syncBuffer=false
08-08 14:25:18.550 18825  5414 W Parcel  : Expecting binder but got null!
08-08 14:25:18.550 18825 18825 D VRI[MainActivity]: draw finished.
08-08 14:25:18.561 18825 18825 D VRI[MainActivity]: onFocusEvent true
08-08 14:25:20.728 18825  5412 I Quality : Blocked msg = Package name: app.revanced.manager.flutter [ schedGroup: 5 schedPolicy: 0 ] process the message: { when=-1s212ms what=0 target=android.os.Handler callback=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0 } took 1210 ms
08-08 14:25:23.753 18825 18825 D VRI[MainActivity]: onFocusEvent false
08-08 14:25:24.986 18825 18825 D VRI[MainActivity]: onFocusEvent true
08-08 14:25:26.757 18825 18825 V AutofillManager: requestHideFillUi(null): anchor = null
08-08 14:25:27.719 18825 18825 V AutofillManager: requestHideFillUi(null): anchor = null
08-08 14:25:29.057 18825  5412 I Quality : Blocked msg = Package name: app.revanced.manager.flutter [ schedGroup: 5 schedPolicy: 0 ] process the message: { when=-1s261ms what=0 target=android.os.Handler callback=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0 } took 1260 ms
08-08 14:25:29.059 18825 18825 I Choreographer: Skipped 75 frames!  The application may be doing too much work on its main thread.
08-08 14:25:29.059 18825 18825 I Quality : Skipped: false 75 cost 1255.6494 refreshRate 16594315 bit true processName app.revanced.manager.flutter
08-08 14:25:29.721 18825 18825 D VRI[MainActivity]: onFocusEvent false
08-08 14:25:29.744 18825 18825 D UxIconPackageManagerExt: loadItemIcon is support edit icon: false
08-08 14:25:29.744 18825 18825 D UxIconPackageManagerExt: UxIcon checkChooseIconsRootPath false
08-08 14:25:31.143 18825  6061 D ColorModeChangeItem: preExecute mColorMode=0,token=android.os.BinderProxy@96d82f0
08-08 14:25:31.188 18825 18825 D VRI[MainActivity]: onFocusEvent true
08-08 14:25:34.663 18825 18825 V AutofillManager: requestHideFillUi(null): anchor = null
08-08 14:25:35.960 18825 18825 D CompatibilityChangeReporter: Compat change id reported: 147798919; UID 10584; state: ENABLED
08-08 14:25:37.659 18825  5412 I Quality : Blocked msg = Package name: app.revanced.manager.flutter [ schedGroup: 5 schedPolicy: 0 ] process the message: { when=-1s20ms what=0 target=android.os.Handler callback=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0 } took 1020 ms
08-08 14:25:38.594 18825 18825 V AutofillManager: requestHideFillUi(null): anchor = null
08-08 14:25:40.001 18825 18825 V AutofillManager: requestHideFillUi(null): anchor = null
08-08 14:25:40.304 18825 18825 D UxIconPackageManagerExt: loadItemIcon is support edit icon: false
08-08 14:25:40.305 18825 18825 D UxIconPackageManagerExt: UxIcon checkChooseIconsRootPath false
08-08 14:25:40.334 18825 18825 D UxIconPackageManagerExt: loadItemIcon is support edit icon: false
08-08 14:25:40.334 18825 18825 D UxIconPackageManagerExt: UxIcon checkChooseIconsRootPath false
08-08 14:25:40.391 18825 18825 D UxIconPackageManagerExt: loadItemIcon is support edit icon: false
08-08 14:25:40.391 18825 18825 D UxIconPackageManagerExt: UxIcon checkChooseIconsRootPath false
08-08 14:25:41.823 18825 18825 V AutofillManager: requestHideFillUi(null): anchor = null
08-08 14:25:41.909 18825 18825 D FilePickerUtils: Allowed file extensions mimes: [application/vnd.android.package-archive]
08-08 14:25:41.910 18825 18825 D FilePickerDelegate: Selected type */*
08-08 14:25:41.958 18825 18825 D VRI[MainActivity]: onFocusEvent false
08-08 14:25:42.073 18825  5435 D VRI[MainActivity]: dispatchAppVisibility visible:false
08-08 14:25:42.089 18825 18825 I SurfaceView: 94088684 surfaceDestroyed
08-08 14:25:42.097 18825  7242 D BufferQueueProducer: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#5(BLAST Consumer)5](id:498900000005,api:1,p:18825,c:18825) disconnect: api 1
08-08 14:25:42.097 18825 18825 D BufferQueueProducer: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#5(BLAST Consumer)5](id:498900000005,api:0,p:-1,c:18825) disconnect: api -1
08-08 14:25:42.097 18825  5414 D SurfaceView: 136306073positionLost mSurfaceControl is null return;
08-08 14:25:42.099 18825  5414 D BufferQueueProducer: [VRI[MainActivity]#4(BLAST Consumer)4](id:498900000004,api:1,p:18825,c:18825) disconnect: api 1
08-08 14:25:42.103 18825 18825 D BufferQueueConsumer: [VRI[MainActivity]#4(BLAST Consumer)4](id:498900000004,api:0,p:-1,c:18825) disconnect
08-08 14:25:42.104 18825 18825 D VRI[MainActivity]: setWindowStopped stopped:true
08-08 14:25:42.107 18825  5435 D BufferQueueConsumer: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#5(BLAST Consumer)5](id:498900000005,api:0,p:-1,c:18825) disconnect
08-08 14:25:42.349 18825  7243 E libEGL  : call to OpenGL ES API with no current context (logged once per thread)
08-08 14:25:42.379 18825 18825 D OplusScrollToTopManager: unregisterGuidePopupDismissReceiverInSystemUI
08-08 14:25:42.379 18825 18825 D OplusScrollToTopManager: Receiver not registered: android.view.OplusScrollToTopManager$1@5567b2f
08-08 14:25:42.380 18825 18825 D OplusScrollToTopManager: unregisterSystemUIBroadcastReceiver 
08-08 14:25:42.380 18825 18825 D OplusScrollToTopManager: java.lang.IllegalArgumentException: Receiver not registered: android.view.OplusScrollToTopManager$2@4b4f53c
08-08 14:25:42.382 18825 18825 V ZoomWindowDecorView: removeZoomView
08-08 14:25:44.071 18825  5435 D ColorModeChangeItem: preExecute mColorMode=0,token=android.os.BinderProxy@96d82f0
08-08 14:25:44.115 18825 18825 D AutofillManager: Fill dialog is enabled:false, hints=[password, passwordAuto, creditCardNumber, creditCardSecurityCode, creditCardExpirationDate]
08-08 14:25:44.121 18825 18825 I InstallPlugin: handleActivityResult(14715,-1,Intent { dat=content://com.android.providers.downloads.documents/... flg=0x1 })
08-08 14:25:44.122 18825 18825 D WindowManager: Add to mViews: DecorView@e97b7f6[MainActivity],pkg= app.revanced.manager.flutter
08-08 14:25:44.126 18825 18825 D InputEventReceiver: Input log is disabled
08-08 14:25:44.443 18825 18825 I Quality : Skipped: false 18 cost 313.88235 refreshRate 16590646 bit true processName app.revanced.manager.flutter
08-08 14:25:44.444 18825 18825 I SurfaceView: 239805068 onAttachedToWindow
08-08 14:25:44.448 18825 18825 D BufferQueueConsumer: [](id:498900000006,api:0,p:-1,c:18825) connect: controlledByApp=false
08-08 14:25:44.448 18825 18825 E IPCThreadState: attemptIncStrongHandle(75): Not supported
08-08 14:25:44.448 18825 18825 E IPCThreadState: attemptIncStrongHandle(66): Not supported
08-08 14:25:44.448 18825 18825 E IPCThreadState: attemptIncStrongHandle(61): Not supported
08-08 14:25:44.448 18825 18825 V ZoomWindowDecorView: setLastReportedMergedConfiguration mZoomDisplayHeight: 2400 getDecorView.244824054
08-08 14:25:44.449 18825  5414 D BufferQueueProducer: [VRI[MainActivity]#6(BLAST Consumer)6](id:498900000006,api:1,p:18825,c:18825) connect: api=1 producerControlledByApp=true
08-08 14:25:44.451 18825 18825 D BufferQueueConsumer: [](id:498900000007,api:0,p:-1,c:18825) connect: controlledByApp=false
08-08 14:25:44.451 18825 18825 I SurfaceView: 239805068 visibleChanged -- surfaceCreated 
08-08 14:25:44.451 18825 10324 D BufferQueueProducer: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#7(BLAST Consumer)7](id:498900000007,api:1,p:18825,c:18825) connect: api=1 producerControlledByApp=true
08-08 14:25:44.453 18825 18825 I SurfaceView: 239805068 surfaceChanged -- format=4 w=1080 h=2400
08-08 14:25:44.457 18825 10323 I flutter : dynamic_color: Core palette detected.
08-08 14:25:44.495 18825 18825 E SurfaceSyncer: Failed to find sync for id=0
08-08 14:25:44.495 18825 18825 D VRI[MainActivity]: registerCallbacksForSync syncBuffer=false
08-08 14:25:44.498 18825  5414 D VRI[MainActivity]: Received frameCommittedCallback lastAttemptedDrawFrameNum=1 didProduceBuffer=true syncBuffer=false
08-08 14:25:44.498 18825  5414 W Parcel  : Expecting binder but got null!
08-08 14:25:44.499 18825 18825 D VRI[MainActivity]: draw finished.
08-08 14:25:44.512 18825 18825 D VRI[MainActivity]: onFocusEvent true
08-08 14:25:46.681 18825  5412 I Quality : Blocked msg = Package name: app.revanced.manager.flutter [ schedGroup: 5 schedPolicy: 0 ] process the message: { when=-1s167ms what=0 target=android.os.Handler callback=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0 } took 1165 ms
08-08 14:25:47.456 18825 18825 V AutofillManager: requestHideFillUi(null): anchor = null
08-08 14:25:50.841 18825  5412 I Quality : Blocked msg = Package name: app.revanced.manager.flutter [ schedGroup: 5 schedPolicy: 0 ] process the message: { when=-1s250ms what=0 target=android.os.Handler callback=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0 } took 1250 ms
08-08 14:25:50.841 18825 18825 V AutofillManager: requestHideFillUi(null): anchor = null
08-08 14:25:50.925 18825 18825 V AutofillManager: requestHideFillUi(null): anchor = null
08-08 14:25:52.674 18825 18825 V AutofillManager: requestHideFillUi(null): anchor = null
08-08 14:25:54.521 18825 18825 V AutofillManager: requestHideFillUi(null): anchor = null
08-08 14:25:55.849 18825 18825 V AutofillManager: requestHideFillUi(null): anchor = null
08-08 14:25:57.099 18825 18825 V AutofillManager: requestHideFillUi(null): anchor = null
08-08 14:25:58.737 18825 18825 V AutofillManager: requestHideFillUi(null): anchor = null
08-08 14:26:03.793 18825 18825 V AutofillManager: requestHideFillUi(null): anchor = null
08-08 14:26:09.066 18825 18825 V AutofillManager: requestHideFillUi(null): anchor = null
08-08 14:26:10.584 18825 18825 V AutofillManager: requestHideFillUi(null): anchor = null
08-08 14:26:11.660 18825 18825 V AutofillManager: requestHideFillUi(null): anchor = null
08-08 14:26:15.028 18825 18825 V AutofillManager: requestHideFillUi(null): anchor = null
08-08 14:26:19.414 18825 18825 V AutofillManager: requestHideFillUi(null): anchor = null
08-08 14:26:19.592 18825 18825 I Quality : Skipped: false 3 cost 55.412964 refreshRate 16571250 bit true processName app.revanced.manager.flutter
08-08 14:26:19.672 18825 18825 D VRI[MainActivity]: onFocusEvent false
08-08 14:26:31.711 18825  5407 D ColorModeChangeItem: preExecute mColorMode=0,token=android.os.BinderProxy@96d82f0
08-08 14:26:31.746 18825 18825 D VRI[MainActivity]: onFocusEvent true
08-08 14:26:33.241 18825 18825 V AutofillManager: requestHideFillUi(null): anchor = null


SECOND LOG:

--------- beginning of system
08-08 14:29:19.035  8710  8710 D OplusInputMethodUtil: init sDebug to false, init sDebugIme to false, init sAlwaysOn to false
08-08 14:29:19.035  8710  8710 D OplusInputMethodUtil: updateDebugToClass InputMethodManager.DEBUG = false
08-08 14:29:19.035  8710  8710 D OplusInputMethodUtil: updateDebugToClass ImeFocusController.DEBUG = false
08-08 14:29:19.035  8710  8710 D OplusInputMethodUtil: updateDebugToClass BaseInputConnection.DEBUG = false
08-08 14:29:19.035  8710  8710 D OplusInputMethodUtil: updateDebugToClass ImeFocusController.sDebugIme = false
08-08 14:29:19.373  8710  8710 I Quality : Skipped: false 18 cost 303.65295 refreshRate 16601866 bit true processName app.revanced.manager.flutter
08-08 14:29:19.395  8710  8710 V ZoomWindowDecorView: setLastReportedMergedConfiguration mZoomDisplayHeight: 2400 getDecorView.196029172
08-08 14:29:19.414  8710  8710 I Quality : Skipped: false 1 cost 28.783592 refreshRate 16601724 bit true processName app.revanced.manager.flutter
08-08 14:29:24.080  8710  8710 D OplusInputMethodManagerInternal: get inputMethodManager extension: com.android.internal.view.IInputMethodManager$Stub$Proxy@a763792
08-08 14:29:28.652  8710  8710 V ZoomWindowDecorView: removeZoomView
08-08 14:29:31.071  8710  8710 D ActivityThread: do gfx trim 40 success
--------- beginning of main
08-08 14:29:32.790  8710  9342 D ColorModeChangeItem: preExecute mColorMode=0,token=android.os.BinderProxy@9fb373c
08-08 14:29:32.826  8710  8710 D AutofillManager: Fill dialog is enabled:false, hints=[password, passwordAuto, creditCardNumber, creditCardSecurityCode, creditCardExpirationDate]
08-08 14:29:32.836  8710  8710 I InstallPlugin: handleActivityResult(967,-1,Intent { dat=content://com.android.providers.downloads.documents/... flg=0x1 })
08-08 14:29:32.837  8710  8710 D WindowManager: Add to mViews: DecorView@39bc3f1[MainActivity],pkg= app.revanced.manager.flutter
08-08 14:29:32.840  8710  8710 D InputEventReceiver: Input log is disabled
08-08 14:29:32.859  8710  8723 W manager.flutter: Cleared Reference was only reachable from finalizer (only reported once)
08-08 14:29:33.251  8710  8710 I Quality : Skipped: false 24 cost 406.26746 refreshRate 16595525 bit true processName app.revanced.manager.flutter
08-08 14:29:33.253  8710  8710 I SurfaceView: 53163551 onAttachedToWindow
08-08 14:29:33.258  8710  8710 D BufferQueueConsumer: [](id:220600000002,api:0,p:-1,c:8710) connect: controlledByApp=false
08-08 14:29:33.258  8710  8710 E IPCThreadState: attemptIncStrongHandle(61): Not supported
08-08 14:29:33.258  8710  8710 E IPCThreadState: attemptIncStrongHandle(57): Not supported
08-08 14:29:33.259  8710  8710 V ZoomWindowDecorView: setLastReportedMergedConfiguration mZoomDisplayHeight: 2400 getDecorView.60539889
08-08 14:29:33.259  8710  8739 D BufferQueueProducer: [VRI[MainActivity]#2(BLAST Consumer)2](id:220600000002,api:1,p:8710,c:8710) connect: api=1 producerControlledByApp=true
08-08 14:29:33.261  8710  8710 D BufferQueueConsumer: [](id:220600000003,api:0,p:-1,c:8710) connect: controlledByApp=false
08-08 14:29:33.261  8710  8710 I SurfaceView: 53163551 visibleChanged -- surfaceCreated 
08-08 14:29:33.261  8710 10995 D BufferQueueProducer: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#3(BLAST Consumer)3](id:220600000003,api:1,p:8710,c:8710) connect: api=1 producerControlledByApp=true
08-08 14:29:33.264  8710  8710 I SurfaceView: 53163551 surfaceChanged -- format=4 w=1080 h=2400
08-08 14:29:33.268  8710 10994 I flutter : dynamic_color: Core palette detected.
08-08 14:29:33.343  8710  8710 E SurfaceSyncer: Failed to find sync for id=0
08-08 14:29:33.343  8710  8710 D VRI[MainActivity]: registerCallbacksForSync syncBuffer=false
08-08 14:29:33.346  8710  8739 D VRI[MainActivity]: Received frameCommittedCallback lastAttemptedDrawFrameNum=1 didProduceBuffer=true syncBuffer=false
08-08 14:29:33.347  8710  8739 W Parcel  : Expecting binder but got null!
08-08 14:29:33.347  8710  8710 D VRI[MainActivity]: draw finished.
08-08 14:29:33.361  8710  8710 D VRI[MainActivity]: onFocusEvent true
08-08 14:29:46.124  8710  8710 V AutofillManager: requestHideFillUi(null): anchor = null
08-08 14:29:47.871  8710  8710 V AutofillManager: requestHideFillUi(null): anchor = null
08-08 14:29:49.339  8710  8710 V AutofillManager: requestHideFillUi(null): anchor = null
```

### Installer logs (exported using Installer menu option) [unneeded if the issue is not during patching].

```shell
N/A
```

### Screenshots or video

https://www.dropbox.com/scl/fi/mw15ykjf0q145uqberqy4/Record_2023-08-08-15-23-30.mp4?rlkey=8kb5tc8ln9iewksvhgu47m03x&dl=0

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by ILoveOpenSourceApplications** [comment]
Was this issue resolved with the merge of commit [`8cb96f1`](https://github.com/ReVanced/revanced-manager/pull/1177/commits/8cb96f1e459f00cca03d46b5ef590e6c28a04718)  in 1177 ?

**Comment by GR3YH4TT3R93** [comment]
Sadly, no.

It's still crashing in the same place.

Luckily it's not my main device so it's not a hige concern if others aren't reporting the same issue but I figured I'd report it just in case.

**Comment by oSumAtrIX** [comment]
Please reopen if still the case.
