### ISSUE TITLE
bug: Occasional black screen when returning to Manager

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [ReVanced/revanced-manager#1635]
### Bug description

This isn't a consistent issue and might be difficult to replicate, but the issue is still there. If the user opens the app, minimizes the app with gesture, opens another app and uses it for some time (sometimes less than a minute) and comes back to ReVanced Manager, only to see a black screen which can be easily fixed by minimizing the app once and returning back immediately. The app functions even if the screen is black.

https://github.com/ReVanced/revanced-manager/assets/117499019/9a1c38b5-f088-4105-9fcc-6e2866b284a0

### Version of ReVanced Manager and version & name of application you tried to patch

ReVanced Manager v1.18.0

### Installation type

Non-root

### Device logs

```shell
Nil
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by validcube** [comment]
👋 Hello,

By how you describe it, this might be an issue with the Flutter Engine (because this behaviour is inconsistent based on your finding) which is out of our scope.

**Comment by oSumAtrIX** [comment]
Inconsistent issues do not necessarily indicate an issue in Flutter engine. What made you say that?

**Comment by ILoveOpenSourceApplications** [comment]
> 👋 Hello,
> 
> By how you describe it, this might be an issue with the Flutter Engine (because this behaviour is inconsistent based on your finding) which is out of our scope.

When I said it's an inconsistent issue and that it's hard to replicate, I meant when the user is trying to replicate it. But if the user is patching an app, decided to let it run in the background while doing something else on the phone, then they decide to check the progress only to see a black screen. In this manner I believe it's much more reproducible.

**Comment by oSumAtrIX** [comment]
I cant replicate this issue, I'll close this for now. If someone else comes across it again, we'll keep it open. It may have been fixed through a dependency update in the meantime this issue was open.

**Comment by Ushie** [comment]
It's in the dev branch, there have been some bugs in the dev branch so we haven't merged it to main yet

**Comment by ILoveOpenSourceApplications** [comment]
> It may have been fixed through a dependency update in the meantime this issue was open.

Can say it's not fixed through any updates in the dev branch so far. Replicating this issue is hard but the issue is still there.

**Comment by ILoveOpenSourceApplications** [comment]
I think this could also be an OS specific thing but I'mnot sure. I'm running OneUI 6.0 on top of Android 14. A long discussion can be seen here https://github.com/flutter/flutter/issues/93276, with this [comment](https://github.com/flutter/flutter/issues/93276#issuecomment-968657291) showing an issue similar to that of mine. In the linked discussion, the issue was replicated in a Samsung, OnePlus and Huawei devices (hence the OS specific assumption).
Steps to replicate (for me):
1) Open Manager.
2) Let it run in the background. 
3) Open another app (in my case Chrome running incognito mode)
4) Browse around for 30-40 seconds.
5) Return back to Manager.
6) Welcomed by a black screen.

Another video:

https://github.com/ReVanced/revanced-manager/assets/117499019/f81351d2-c70c-4e91-968a-488a52a4ada0
