### ISSUE TITLE
bug: Patched app won't appear in Patched app list if you leave the installation screen

### ISSUE THREAD

**Issue by KobeW50** [ReVanced/revanced-manager#2783]
### Bug description

If you exit the Installation screen before the installation is complete, the Manager doesn't know that the app is a patched app, and so it doesn't display in the Apps screen.

https://github.com/user-attachments/assets/22a494ee-e58b-4b5b-8272-eff4933aa8a1

### Version of ReVanced Manager and version & name of app you are patching

1.26.0-dev.1

### Installation method

None

### ReVanced Manager logs

[revanced-manager_logcat_2025-10-03T12_37_07.189715.txt](https://github.com/user-attachments/files/22684567/revanced-manager_logcat_2025-10-03T12_37_07.189715.txt)

### Patch logs

```shell

```

### Solution

I'm guessing that in the installation screen the Manager is waiting for a response from the OS about the status of the install. If this is the case, the Manager should just continue to wait for this response even after leaving the installation screen.

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.
- [x] The bug is only related to ReVanced Manager.

**Comment by Axelen123** [comment]
Fixed by https://github.com/ReVanced/revanced-manager/commit/2ff70728b490b92f212a82dcf599bc0c23f589e7

**Comment by hulinhao233** [comment]
The issue still persists. After patching the APK and installing it, ReVanced shows that the user installation was aborted.
