### ISSUE TITLE
bug:  （Solved: problems caused by Google）revanced-manager seems to break the package validation of the android

### ISSUE THREAD

**Issue by Seshiria** [revanced/revanced-manager#661]
### Type

Other

### Bug description

I patched the old version of youtube music, and then prepared to upgrade to the new version of youtube music. I found that youtube music could no longer be installed/overwritten.

Install youtube music prompt "PackageInstallerSession: Marking session 1136869388 as failed: INSTALL_FAILED_VERIFICATION_FAILURE: Integrity check failed for file:///data/app/vmdl1136869388.tmp ...”A complete log will be attached.

I try to unpatch in the advanced-manager and then continue the installation, and uninstall youtube music and then reinstall it, both of which prompt: "INSTALL_FAILED_VERIFICATION_FAILURE"

Now I can't install youtube music (.apk flie  or google play store ) anywhere on my device:
[log.txt](https://github.com/revanced/revanced-manager/files/10497345/log.txt)

This is the logcat that I tried to install from music on Google Play. Now I don't have the app youtube music on my device

Of course, I also tried to restart Android and clear Google play data

### Steps to reproduce

1.Fix the old version of youtube musicand install it with root(ps old version yt music is
v5.36.51)
2.Try to install a new unmodified youtube music(new version is v5.39.52 and v5.5.41.50)

### Android version

android 13

### Manager version

0.0.53

### Target package name

youtube music

### Target package version.

5.39.52

### Installation type

Root

### Patches selected.

Patches used before:
background play
codecs unlock
hide get premium
minmized playback music
music video ads

### Device logs (exported using Manager settings).

```shell
01-25 15:35:54.977 30704 30704 I Finsky  : [2] adkq.c(8): VerifyApps:, Install-time verification requested for package com.google.android.apps.youtube.music, id = 16
01-25 15:35:54.982 30704 21257 I Finsky  : [448] VerifyAppsInstallTask.agG(3): VerifyApps: Anti-malware verification task started for package=com.google.android.apps.youtube.music
01-25 15:35:54.983 30704 21257 I Finsky  : [448] VerifyAppsInstallTask.agG(9): VerifyApps: Skipping verification because own installation
01-25 15:35:54.983 30704 21257 I Finsky  : [448] VerifyAppsInstallTask.agG(154): VerifyApps: Skipping anti malware verification (preconditions not met). package=com.google.android.apps.youtube.music
01-25 15:35:54.984 30704 21257 I Finsky  : [448] VerifyPerSourceInstallationConsentInstallTask.agG(17): PSIC verification started with installer uid: 10021 package name: com.android.vending, originating uid: -1
01-25 15:35:54.987 30704 21257 I Finsky  : [448] VerifyPerSourceInstallationConsentInstallTask.agG(39): Skipping logging for attempted installation. This is a Play Store installation.
01-25 15:35:54.988 30704 30704 I Finsky  : [2] VerifyInstallTask.h(2): VerifyApps: Verification stage already finished, ignoring sub-task callback, id=16
01-25 15:35:54.988 30704 30704 I Finsky  : [2] VerifyInstallTask.j(2): VerifyApps: Returning package verification result id=16, result=ALLOW
01-25 15:35:54.990 30704 30704 I Finsky  : [2] VerifyInstallTask.agF(7): VerifyApps: Verification complete: id=16, package_name=com.google.android.apps.youtube.music
01-25 15:35:55.007  1714 18443 I LSPosed-Bridge: [ INFO] 01-25 15:35:55 (PmsHookTarget33) @shouldFilterApplication: query from com.android.vending
01-25 15:35:55.007  1714  2547 I AppIntegrityManagerServiceImpl: Integrity check of com.google.android.apps.youtube.music result: DENY due to [Rule: (PACKAGE_NAME EQ FE442C19021F749808DC95BDAF40118476FC2E64F2A35EDFE6221C51D27AF4DA) AND (VERSION_CODE GTE 24154330) AND NOT (APP_CERTIFICATE EQ A2A1AD7BA7F41DFCA4514E2AFEB90691719AF6D0FDBED4B09BBF0ED897701CEB) OR (APP_CERTIFICATE EQ CA7CDF89092B2C185FD34135C27AF890364890063D88474780DF65A5685CD311), DENY]
01-25 15:35:55.008  1714  1961 D PackageInstallerSession: Marking session 1136869388 as failed: INSTALL_FAILED_VERIFICATION_FAILURE: Integrity check failed for file:///data/app/vmdl1136869388.tmp
01-25 15:35:55.011  1714  2404 E PackageInstallerSession: Failed to verify session 1136869388
01-25 15:35:55.013 30704 30704 I Finsky  : [2] ocm.e(1): Submitter: commit of com.google.android.apps.youtube.music failed with 6002
01-25 15:35:55.013 30704 30704 E Finsky  : [2] ocm.e(2): Submitter: commit error message INSTALL_FAILED_VERIFICATION_FAILURE: Integrity check failed for file:///data/app/vmdl1136869388.tmp
01-25 15:35:55.018 30704 21274 E Finsky  : [461] nrg.a(5): IV2: Task Failed: tid:1000000105, statusCode:6002
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by Seshiria** [comment]
This is the of installation using shell pm:
````
Failure [INSTALL_FAILED_VERIFICATION_FAILURE: Integrity check failed for file:///data/app/vmdl289107883.tmp]
````
log:
````
01-25 16:42:11.796 30704 30704 I Finsky  : [2] adkq.c(8): VerifyApps:, Install-time verification requested for package com.google.android.apps.youtube.music, id = 20
01-25 16:42:11.803 30704  2121 I Finsky  : [558] VerifyAppsInstallTask.agG(3): VerifyApps: Anti-malware verification task started for package=com.google.android.apps.youtube.music
01-25 16:42:11.808 30704  2121 I Finsky  : [558] adou.a(7): Single user settings service is not running, bind it now
01-25 16:42:11.814 30704 30704 I Finsky  : [2] nll.onServiceConnected(5): Single user settings service is connected
01-25 16:42:11.825 30704  2121 W Settings: Setting install_non_market_apps has moved from android.provider.Settings.Global to android.provider.Settings.Secure, returning read-only value.
01-25 16:42:11.836  1714  2547 I AppIntegrityManagerServiceImpl: Integrity check of com.google.android.apps.youtube.music result: DENY due to [Rule: (PACKAGE_NAME EQ FE442C19021F749808DC95BDAF40118476FC2E64F2A35EDFE6221C51D27AF4DA) AND (VERSION_CODE GTE 24154330) AND NOT (APP_CERTIFICATE EQ A2A1AD7BA7F41DFCA4514E2AFEB90691719AF6D0FDBED4B09BBF0ED897701CEB) OR (APP_CERTIFICATE EQ CA7CDF89092B2C185FD34135C27AF890364890063D88474780DF65A5685CD311), DENY]
01-25 16:42:11.837 30704  2121 W PackageParser: Unknown element under <manifest>: queries at /data/app/vmdl289107883.tmp/base.apk Binary XML file line #119
01-25 16:42:12.578     0     0 E [20230125_16:42:12.576962]@0 FG: fg_psy_get_property: unsupported property 76
01-25 16:42:12.584     0     0 E [20230125_16:42:12.583698]@7 FG: fg_psy_get_property: unsupported property 76
01-25 16:42:12.590     0     0 W [20230125_16:42:12.589936]@6 healthd: battery l=35 v=4054 t=18.3 h=2 st=2 c=342000 fc=2878000 cc=0 chg=u
01-25 16:42:12.596     0     0 E [20230125_16:42:12.595628]@6 FG: fg_psy_get_property: unsupported property 76
01-25 16:42:12.604  2802  3646 D PowerUI : can't show warning due to - plugged: true status unknown: false
01-25 16:42:12.604  3369  3369 D QtiCarrierConfigHelper: WARNING, no carrier configs on phone Id: 0
01-25 16:42:12.606 19672 19672 W Notification: Use of stream types is deprecated for operations other than volume control
01-25 16:42:12.606 19672 19672 W Notification: See the documentation of setSound() for what to use instead with android.media.AudioAttributes to qualify your playback use case
01-25 16:42:12.607  1714  1751 W ActivityManager: Foreground service started from background can not have location/camera/microphone access: service com.slash.batterychargelimit/.ForegroundService
01-25 16:42:12.622 30704  2121 I Finsky  : [558] lvc.e(3): Task 7 requested foreground
01-25 16:42:12.623 30704  2121 I Finsky  : [558] lvc.e(8): Not entering foreground
01-25 16:42:12.629 30704 30751 D TrafficStats: tagSocket(181) with statsTag=0xc9395b26, statsUid=-1
01-25 16:42:12.632 30704 30751 D TrafficStats: tagSocket(187) with statsTag=0xc9395b26, statsUid=-1
01-25 16:42:12.632  5226 17685 I GoLog   : udp:127.0.0.1:42912 accepted udp:198.19.20.27:443 [socks -> proxy]
01-25 16:42:12.636  5226 17680 I GoLog   : tcp:127.0.0.1:37173 accepted tcp:198.19.20.27:443 [socks -> proxy]
01-25 16:42:12.651  3310  5123 W HidlServiceManagement: Waited one second for com.qualcomm.qti.uceservice@2.3::IUceService/com.qualcomm.qti.uceservice
01-25 16:42:12.651   693   693 I hwservicemanager: Since com.qualcomm.qti.uceservice@2.3::IUceService/com.qualcomm.qti.uceservice is not registered, trying to start it as a lazy HAL.
01-25 16:42:12.651  3310  5123 I HidlServiceManagement: getService: Trying again for com.qualcomm.qti.uceservice@2.3::IUceService/com.qualcomm.qti.uceservice...
01-25 16:42:12.653   693  2194 W libc    : Unable to set property "ctl.interface_start" to "com.qualcomm.qti.uceservice@2.3::IUceService/com.qualcomm.qti.uceservice": error code: 0x20
01-25 16:42:12.654     0     0 E [20230125_16:42:12.653541]@0 init: Control message: Could not find 'com.qualcomm.qti.uceservice@2.3::IUceService/com.qualcomm.qti.uceservice' for ctl.interface_start from pid: 693 (/system/bin/hwservicemanager)
01-25 16:42:12.654   693  2194 I hwservicemanager: Tried to start com.qualcomm.qti.uceservice@2.3::IUceService/com.qualcomm.qti.uceservice as a lazy service, but was unable to. Usually this happens when a service is not installed, but if the service is intended to be used as a lazy service, then it may be configured incorrectly.
01-25 16:42:12.709  3830   883 E WakeLock: GCM_HB_ALARM release without a matched acquire!
01-25 16:42:12.709  3830   883 W WakeLock: GCM_HB_ALARM counter does not exist
01-25 16:42:12.712  1714  2605 D ConnectivityService: reportNetworkConnectivity(100, false) by 10028
01-25 16:42:12.713  3830   883 I AlarmManager: setExactAndAllowWhileIdle [name: GCM_CONN_ALARM type: 2 triggerAtMillis: 73146454]
01-25 16:42:12.714  3352  5173 D NetworkMonitor/100: Forcing reevaluation for UID 10028. Dns signal count: 0
01-25 16:42:12.716  3830   883 E WakeLock: GCM_CONN_ALARM release without a matched acquire!
01-25 16:42:12.716  3830   883 W WakeLock: GCM_CONN_ALARM counter does not exist
01-25 16:42:12.720  3352  2197 D TrafficStats: tagSocket(104) with statsTag=0xffffff81, statsUid=-1
01-25 16:42:12.720  3352  2196 D TrafficStats: tagSocket(68) with statsTag=0xffffff81, statsUid=-1
01-25 16:42:12.725  3352  2196 D TrafficStats: tagSocket(68) with statsTag=0xffffff81, statsUid=-1
01-25 16:42:12.726  3352  2197 D TrafficStats: tagSocket(105) with statsTag=0xffffff81, statsUid=-1
01-25 16:42:12.732  3352  3352 D TrafficStats: tagSocket(104) with statsTag=0xffffffff, statsUid=-1
01-25 16:42:12.734  3352  2197 D NetworkMonitor/100: PROBE_DNS connectivitycheck.gstatic.cn 14ms OK 120.253.255.98
01-25 16:42:12.734  3352  3352 D TrafficStats: tagSocket(68) with statsTag=0xffffffff, statsUid=-1
01-25 16:42:12.735  3352  2196 D NetworkMonitor/100: PROBE_DNS connectivitycheck.gstatic.cn 16ms OK 120.253.255.98
01-25 16:42:12.738  3352  2197 D TrafficStats: tagSocket(68) with statsTag=0xffffff81, statsUid=-1
01-25 16:42:12.739  3352  2196 D TrafficStats: tagSocket(104) with statsTag=0xffffff81, statsUid=-1
01-25 16:42:12.821  5226 17576 I GoLog   : Using Prepared: 81.28.12.12
01-25 16:42:12.824  5226 17682 I GoLog   : Using Prepared: 81.28.12.12
01-25 16:42:12.851  3352  2197 D NetworkMonitor/100: PROBE_HTTP http://connectivitycheck.gstatic.cn/generate_204 time=115ms ret=204 request={Connection=[close], User-Agent=[Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.32 Safari/537.36]} headers={null=[HTTP/1.1 204 No Content], Connection=[close], Content-Length=[0], Cross-Origin-Resource-Policy=[cross-origin], Date=[Wed, 25 Jan 2023 08:42:13 GMT], X-Android-Received-Millis=[1674636132849], X-Android-Response-Source=[NETWORK 204], X-Android-Selected-Protocol=[http/1.1], X-Android-Sent-Millis=[1674636132779]}
01-25 16:42:12.938  5226 17682 I GoLog   : udp:127.0.0.1:42912 accepted udp:198.19.20.27:443 [socks -> proxy]
01-25 16:42:12.982  3352  2196 D NetworkMonitor/100: PROBE_HTTPS https://connectivitycheck.gstatic.cn/generate_204 time=245ms ret=204 request={Connection=[close], User-Agent=[Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.32 Safari/537.36]} headers={null=[HTTP/1.1 204 No Content], Alt-Svc=[h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"], Connection=[close], Content-Length=[0], Cross-Origin-Resource-Policy=[cross-origin], Date=[Wed, 25 Jan 2023 08:42:13 GMT], X-Android-Received-Millis=[1674636132980], X-Android-Response-Source=[NETWORK 204], X-Android-Selected-Protocol=[http/1.1], X-Android-Sent-Millis=[1674636132873]}
01-25 16:42:12.985  3352  2195 D NetworkMonitor/100: isCaptivePortal: isSuccessful()=true isPortal()=false RedirectUrl=null isPartialConnectivity()=false Time=268ms
01-25 16:42:12.988  1714  2605 D ConnectivityService: [100 WIFI] validation passed
01-25 16:42:13.135  5226 17576 I GoLog   : Using Prepared: 81.28.12.12
01-25 16:42:13.651  3310  5123 W HidlServiceManagement: Waited one second for com.qualcomm.qti.uceservice@2.3::IUceService/com.qualcomm.qti.uceservice
01-25 16:42:13.652   693   693 I hwservicemanager: Since com.qualcomm.qti.uceservice@2.3::IUceService/com.qualcomm.qti.uceservice is not registered, trying to start it as a lazy HAL.
01-25 16:42:13.653  3310  5123 I HidlServiceManagement: getService: Trying again for com.qualcomm.qti.uceservice@2.3::IUceService/com.qualcomm.qti.uceservice...
01-25 16:42:13.656     0     0 E [20230125_16:42:13.655210]@0 init: Control message: Could not find 'com.qualcomm.qti.uceservice@2.3::IUceService/com.qualcomm.qti.uceservice' for ctl.interface_start from pid: 693 (/system/bin/hwservicemanager)
01-25 16:42:13.656   693  2204 W libc    : Unable to set property "ctl.interface_start" to "com.qualcomm.qti.uceservice@2.3::IUceService/com.qualcomm.qti.uceservice": error code: 0x20
01-25 16:42:13.656   693  2204 I hwservicemanager: Tried to start com.qualcomm.qti.uceservice@2.3::IUceService/com.qualcomm.qti.uceservice as a lazy service, but was unable to. Usually this happens when a service is not installed, but if the service is intended to be used as a lazy service, then it may be configured incorrectly.
01-25 16:42:14.520 30704  2123 I Finsky  : [560] adjs.c(3): VerifyApps: Verification package=com.google.android.apps.youtube.music, id=20, response=0, upload_requested=false
01-25 16:42:14.531 30704  2121 I Finsky  : [558] VerifyPerSourceInstallationConsentInstallTask.agG(17): PSIC verification started with installer uid: 0 package name: null, originating uid: -1
01-25 16:42:14.536 30704 30704 I Finsky  : [2] VerifyInstallTask.j(2): VerifyApps: Returning package verification result id=20, result=ALLOW
01-25 16:42:14.539  1714  1961 D PackageInstallerSession: Marking session 289107883 as failed: INSTALL_FAILED_VERIFICATION_FAILURE: Integrity check failed for file:///data/app/vmdl289107883.tmp
01-25 16:42:14.540 30704 30704 I Finsky  : [2] VerifyInstallTask.agF(7): VerifyApps: Verification complete: id=20, package_name=com.google.android.apps.youtube.music
01-25 16:42:14.541  1714  2404 E PackageInstallerSession: Failed to verify session 289107883
01-25 16:42:14.653  3310  5123 W HidlServiceManagement: Waited one second for com.qualcomm.qti.uceservice@2.3::IUceService/com.qualcomm.qti.uceservice
````

**Comment by oSumAtrIX** [comment]
Please include all steps you did to uninstall the app and install the unpatched app.

**Comment by Seshiria** [comment]
> Please include all steps you did to uninstall the app and install the unpatched app.

Sorry, because it took several weeks from v5.36.51 to v5.39.52, I can't be sure what happened on the way. Because only youtube music is damaged and only revanced is used to patch youtube music, I open this issus here. If I recall more details or find other content, I will add here

Here are the solutions I have tried:

* adb shell pm install （-r -f）
* google play store install/update
* File manager, use the system installer to install apk
* File manager, calling SAI installation

Now the above installation is the same error:INSTALL_FAILED_VERIFICATION_FAILURE

**Comment by oSumAtrIX** [comment]
Try the following steps precisely:

1. Uninstall the app via pm for all users
2. Install the original app

Report back which steps and commands you did exactly.

**Comment by Seshiria** [comment]
This is all the command lines I execute:
````
127|OnePlus5:/cache # date
Fri Jan 27 23:54:25 CST 2023
OnePlus5:/cache # id
uid=0(root) gid=0(root) groups=0(root) context=u:r:magisk:s0
OnePlus5:/cache # pm list users
Users:
        UserInfo{0:name:c13} running
OnePlus5:/cache # pm uninstall --user 0 com.google.android.apps.youtube.music
Failure [not installed for 0]
1|OnePlus5:/cache # pm uninstall com.google.android.apps.youtube.music
Failure [DELETE_FAILED_INTERNAL_ERROR]
1|OnePlus5:/cache # pm install youtube-music-5-39-52.apk
Failure [INSTALL_FAILED_VERIFICATION_FAILURE: Integrity check failed for file:///data/app/vmdl143697783.tmp]
1|OnePlus5:/cache # sha256sum  youtube-music-5-39-52.apk
4c3ad6aa0cf9a21a2342790155b32cdff482449ca4f96b79f9d565420662a289  youtube-music-5-39-52.apk
OnePlus5:/cache # date
Fri Jan 27 23:55:06 CST 2023
````
This part is the log captured by logcat at the same time,Too many lines, put in file:[logcat.txt](https://github.com/revanced/revanced-manager/files/10520720/logcat.txt)

**Comment by lucasyvas** [comment]
After patching YouTube to 18.03.36 I also can no longer install regular YouTube from the play store.

Had the same reverse issue before, where I couldn't install the patched version because there was a conflict with the regular play store version. I "uninstalled" the regular YouTube updates via play store and that let me install the patched YouTube, but now I cannot update regular YouTube :/

There is some conflict between the revanced and regular versions.

**Comment by oSumAtrIX** [comment]
This should been fixed with https://github.com/revanced/revanced-patches/pull/1553/commits/3d1cce5b4ca54c622b863f24febeb03a6060033c. Please confirm.

**Comment by Seshiria** [comment]
> This should been fixed with [revanced/revanced-patches@3d1cce5](https://github.com/revanced/revanced-patches/commit/3d1cce5b4ca54c622b863f24febeb03a6060033c). Please confirm.

The "youtube music revanced" patched with "music-micro-support" can be installed normally, but the package name has been modified. I think this patch does not fix the problem raised by this issue.

It was originally to use Google Play to install youtube music, and then use revanced install as root

**Comment by oSumAtrIX** [comment]
If you have root, you can mount the app without having to use the microg-support patch.

**Comment by Seshiria** [comment]
> If you have root, you can mount the app without having to use the microg-support patch.

The current situation is that I used root as install youtube music revanced before, and the android system now prevents me from installing/updating youtube music. Even if unpatch is completely uninstalled, the official version of youtube music cannot continue to be installed.

This should been fixed with https://github.com/revanced/revanced-patches/commit/3d1cce5b4ca54c622b863f24febeb03a6060033c is https://github.com/revanced/revanced-manager/issues/661#issuecomment-1407513029 ?

**Comment by oSumAtrIX** [comment]
If you uninstalled the app from the device properly, then it is not possible to conflict. If it does, then you have not uninstalled the app properly or your ROM has an issue.

**Comment by Seshiria** [comment]
> If you uninstalled the app from the device properly, then it is not possible to conflict. If it does, then you have not uninstalled the app properly or your ROM has an issue.

I tried to operate under the shell using root:https://github.com/revanced/revanced-manager/issues/661#issuecomment-1406701684

My guess is that the package manager of the system is damaged. Maybe we should check all the operations performed by the Revanced “root as install”.

**Comment by oSumAtrIX** [comment]
ReVanced does not use the package manager for mounting.

**Comment by Seshiria** [comment]
I found the root cause of the problem:https://hitechglitz.com/because-of-this-some-google-app-updates-fail-to-sideload-on-android-11/

Solution: 
1. Rename /data/system/integrity_ rules/rules
2. Then install apk,

Use renaming instead of deleting files. If you have any problems, please restore the files. I don't want to damage unknown things:)


thank @oSumAtrIX

**Comment by pmsobrado** [comment]
I'm also getting INSTALL_FAILED_VERIFICATION_FAILURE on Android 10, MIUI 12 (xiaomi.eu ROM). I don't have /data/system/integrity_ rules/ folder. I tried uninstalling with ADB, it did not work. I guess I have a leftover somewhere.

Any help?
