### ISSUE TITLE
Stuck after successfully patching and installing.

### ISSUE THREAD

**Issue by estebanxz** [revanced/revanced-manager#67]
### Type

Functionality

### Branch

Flutter

### Issue

![Screenshot_20220914-163307](https://user-images.githubusercontent.com/65878342/190247381-7108b2a9-d2a1-4fff-a1fd-80dd84070e32.jpg)

After patching and installing an app, screen gets stuck (shown in photo). I tried giving the manager all permissions and also disabling any battery optimizations, tried again from the beginning but the result is the same. This prevents the successfully installed app from being detected by the manager.

### Feature

If this is fixed it'll enable the installed apps to appear under "installed apps" and it will help to keep the patched app itself updated.

### Motivation

Because it's an essential part of the functionality of the app.

### Additional context

For additional context refer to

https://discord.com/channels/952946952348270622/1019692986096955523

**Comment by Aunali321** [comment]
Go to settings and hold About about section and paste it here.

**Comment by estebanxz** [comment]
> Go to settings and hold About about section and paste it here.

Version: 0.0.1
Model: SM-N975F
Android Version: 12
Arch: arm64-v8a

**Comment by SpookieGames** [comment]
I have the same issue

Version: 0.0.1
Model: 2201116SG
Android Version: 12
Arch: arm64-v8a

**Comment by ponces** [comment]
Should be fixed on https://github.com/revanced/revanced-manager/commit/9f3a30d9f2d06f00250623142a7e2e2c119d4aaa.

**Comment by SpookieGames** [comment]
From what I can see it is still not working as indented on 0.0.6

**Comment by estebanxz** [comment]
Yes can confirm, issue persists as of 0.0.6, can the issue be reopened?

**Comment by SpookieGames** [comment]
@ponces the issue has not been fixed can you reopen this thread?

**Comment by ponces** [comment]
Did you allow unknown install apps for Manager?

**Comment by SadLinusGuy0** [comment]
> He can install the patched YouTube but the manager doesn't recognize it that it has been installed
> 
> Edit: I even allowed it to see installed apps

Same thing for me, I have YT, YT Music and Tiktok install but only shows YouTube and Tiktok

**Comment by estebanxz** [comment]
> @estebanxz 
> Did you allow unknown install apps for Manager?

Yes, all permissions including media access and installation of apps from unknown sources (in this case manager) are allowed, I tried multiple times, clearing data, reinstalling, same result.

**Comment by SpookieGames** [comment]
I found a workaround for now.

You basically want to install the apk you downloaded and then select app and patch normally. When patched you can remove the original YouTube and leave the patched one installed and now it shows it in the installed screen

**Comment by harry590** [comment]
Mine problem same manager doesnot recognise the installed patched youtube apk file, all permissions given.

**Comment by harry590** [comment]
> I found a workaround for now.
> 
> You basically want to install the apk you downloaded and then select app and patch normally. When patched you can remove the original YouTube and leave the patched one installed and now it shows it in the installed screen 

Unable to install youtube 17.33.42 over latest youtube, says package invalid.

**Comment by SpookieGames** [comment]
Forgot to mention that if you have YouTube preinstalled it won't work as this version is older and you can't downgrade apps. Also the App signature might be different

**Comment by harry590** [comment]
> Forgot to mention that if you have YouTube preinstalled it won't work as this version is older and you can't downgrade apps. Also the App signature might be different 

I have removed the youtube over adb and tried to install youtube v.17.33.42 but still same issue that package invalid.

**Comment by SpookieGames** [comment]
You have to install the full apk and not the split APK file .xapk

**Comment by harry590** [comment]
> You have to install the full apk and not the split APK file .xapk

I have managed to install youtube 17.33.42 and revanced manager also showing in patched applications.

**Comment by estebanxz** [comment]
As of 0.0.10 this issue seems to be fixed (albeit with a side-effect) I uninstalled everything, installed manager and proceeded to patch YouTube, it patched successfully and after install I was at the main menu and the app was there, the issue now is the duplication of installed apps in manager, which is already documented.

**Comment by ponces** [comment]
Those are not duplicates. You have installed ReVanced version of YouTube Music in parallel with an existing installtion of regular YouTube Music right?

**Comment by estebanxz** [comment]
> Those are not duplicates. You have installed ReVanced version of YouTube Music in parallel with an existing installtion of regular YouTube Music right?

Nope, for YouTube that could be somewhat true (pre-installed YouTube app that is disabled) but i don't have YouTube music installed and that will too duplicate in the installed apps screen, so I don't see that being the reason of the issue.

**Comment by ponces** [comment]
Those are not duplicates. You have installed ReVanced version of YouTube Music in parallel with an existing installtion of regular YouTube Music right?

**Comment by ponces** [comment]
> Nope, for YouTube that could be somewhat true (pre-installed YouTube app that is disabled) but i don't have YouTube music installed and patched version will too duplicate in the installed apps screen, so I don't see that being the reason of the issue.

Ok. I'll take a look into it. Thanks

**Comment by ponces** [comment]
Duplicates should be fixed on incoming v0.0.11.

**Comment by harry590** [comment]
> Duplicates should be fixed on incoming v0.0.11.

I also have same duplication upto 5 or 6 times in manager v0.0.13. I do have youtube preinstalled.![Screenshot_20220918-140052.jpg](https://user-images.githubusercontent.com/66207112/190893234-19ec7c4e-9e84-473d-8eb2-8a1a1ee9a6df.jpg)

**Comment by SpookieGames** [comment]
I don't think they will remove by themselves you probably have to reinstall the manager

**Comment by harry590** [comment]
> I don't think they will remove by themselves you probably have to reinstall the manager 

Yep i think so bec everytime manager is updated it creates duplicates like that.

**Comment by ponces** [comment]
Clean manager data or uninstall and start it over. This is fixed now. But currently saved manager data can still keep this duplicates.

**Comment by St3ph32** [comment]
As for the OP problem, this still exists. Tested on the latest version 0.0.26.
You can use ADB at the moment of the installation as a workaround, but it seems that even if the app appears on the manager it won't be checked if an update is available, it will keep staying on the Installed tab.

**Comment by ILoveOpenSourceApplications** [comment]
Does this still exist on the latest version of manager?

**Comment by nik0pic0** [comment]
I was having the same issue, but I realized what the issue is. When you hit install, the OS will warn you saying "installing this app could be harmful for your device!"

The main button available will say "Got It!", but this actually just prevents the installation of the .apk

Instead, you need to hit the drop down in the warning pop up and there should be a button that say "install anyway".
