### ISSUE TITLE
navigation bar color.

### ISSUE THREAD

**Issue by danieloox** [revanced/revanced-manager#98]
### Type

Cosmetic

### Branch

flutter

### Issue

White navbar on dark mode.

### Feature

Make this dark in dark mode :)
![20220915_124050](https://user-images.githubusercontent.com/113600273/190391039-a32dad1b-e8c0-4bec-b9da-213ea59ff055.jpg)

### Motivation

better look :)

**Comment by ponces** [comment]
Fixed with https://github.com/revanced/revanced-manager/commit/9f58757cafa2e36ff0660cb63f983666ecbd3957.

**Comment by FabiRich** [comment]
I have updated to the newest version, but experiencing the issue still. But Miui is the problem here too.
![Screenshot_2022-09-16-01-33-36-784_app revanced manager flutter](https://user-images.githubusercontent.com/76914324/190527327-f129ab3c-20d6-48be-9ca0-9930b23a1541.jpg)

And a link to a similar issue https://github.com/florisboard/florisboard/issues/1694

**Comment by danieloox** [comment]
maybe is a miui problem. 0.0.7 navbar works fine for me. dark is dark white is white.

**Comment by Spacellary** [comment]
### 0.0.7 MIUI 13 (Android 11)
![Screenshot_2022-09-16-08-39-25-787_app revanced manager flutter](https://user-images.githubusercontent.com/39604793/190630828-6f2892ef-c284-4e5c-b79c-5de5829f4992.jpg)

Seems fine here, even though I'd not normally notice since I think most people use Fullscreen/Gesture navigation? xD

**Comment by FabiRich** [comment]
https://user-images.githubusercontent.com/76914324/190730626-9bff9822-362e-4354-b6c3-f26b60155f82.mp4


I tested it and it only appears on the dark mode of Miui, but I can see a sligh difference, when turning in on and off in the ReVanced Manager settings. And yes I usually use gestures too, but wanted to check this issue

**Comment by ponces** [comment]
Feature is implemented.
Not Manager's fault that OS can't handle this.
Closed.
